export const ADD_PATH = 'APP/ADD_PATH'
export const SELECT_PATH = 'APP/SELECT_PATH'
export const HANDLE_FAVORITES = 'APP/HANDLE_FAVORITES'
export const HANDLE_DELETE_PATH = 'APP/HANDLE_DELETE_PATH'
export const HANDLE_SEARCH = 'SEARCH/HANDLE_SEARCH'
export const GET_PATHES = 'FIREBASE/GET_PATHES'
export const ADD_PATH_ASYNC = 'FIREBASE/ADD_PATH_ASYNC'
export const DELETE_PATH_ASYNC = 'FIREBASE/DELETE_PATH_ASYNC'

